apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - nodeports.yaml
  - gateway-nodeport.yaml
  - secret.example.yaml

patches:
  - path: patch-ui-auth.yaml
  - path: patch-pod-name.yaml

images:
  - name: ghcr.io/peterrauscher/chrome-cell
    newTag: latest
  - name: ghcr.io/peterrauscher/chrome-cell-gateway
    newTag: latest
