apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chrome-cell

resources:
  - namespace.yaml
  - configmap.yaml
  - statefulset.yaml
  - service-headless.yaml
  - service-cdp.yaml
  - networkpolicy.yaml
  - gateway.yaml
